# Hugging Face API
hf.api.key=${HF_API_KEY:}
hf.api.url=https://router.huggingface.co/v1/chat/completions

# CoinGecko API
coingecko.api.key=${COINGECKO_API_KEY:}

# NewsAPI
newsapi.api.key=${NEWSAPI_API_KEY:db3fa4a7213747308677c4896c34c932}

# Firebase / Firestore
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:}
firebase.project-id=${FIREBASE_PROJECT_ID:cryptodash-dbb5d}
firebase.firestore.locations-collection=${FIREBASE_LOCATIONS_COLLECTION:crypto_locations}
firebase.firestore.database-id=${FIREBASE_DATABASE_ID:default}
